# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: pancakeswap
rollback_on_reorg: true
unordered_multichain_mode: true
contracts:
  - name: PancakeV3Factory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: PancakeV3Pool
    handler: src/EventHandlers.ts
    events:
      - event: Initialize(uint160 sqrtPriceX96, int24 tick)
      - event: Collect(address indexed owner, address recipient, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount0, uint128 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
      - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
      - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
      - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from

networks:
  - id: 1 # Ethereum Mainnet
    start_block: 0
    contracts:
      - name: PancakeV3Factory
        address: 0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865
      - name: PancakeV3Pool
  - id: 56 # bsc
    start_block: 0
    contracts:
      - name: PancakeV3Factory
        address: 0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865
      - name: PancakeV3Pool
  # - id: 42161 # Arbitrum One
  #   start_block: 0
  #   contracts:
  #     - name: PancakeV3Factory
  #       address: 0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865
  #     - name: PancakeV3Pool
  # - id: 10 # Optimism
  #   start_block: 0
  #   contracts:
  #     - name: PancakeV3Factory
  #       address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
  #     - name: PancakeV3Pool
  # - id: 8453 # base
  #   start_block: 0
  #   contracts:
  #   - name: PancakeV3Factory
  #     address: 0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865
  #   - name: PancakeV3Pool
# - id: 137 # polygon
#   start_block: 0
#   contracts:
#   - name: PancakeV3Factory
#     address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
#   - name: PancakeV3Pool
# - id: 43114 # avalanche
#   start_block: 0
#   contracts:
#   - name: PancakeV3Factory
#     address: 0x740b1c1de25031C31FF4fC9A62f554A55cdC1baD
#   - name: PancakeV3Pool
  # - id: 81457 # blast
  #   start_block: 0
  #   contracts:
  #   - name: PancakeV3Factory
  #     address: 0x0bfbcf9fa4f9c56b0f40a671ad40e0805a091865
  #   - name: PancakeV3Pool
# # - id: 7777777 # Zora
# #   start_block: 0
# #   contracts:
# #   - name: PancakeV3Factory
# #     address: 0x7145f8aeef1f6510e92164038e1b6f8cb2c42cbb
# #   - name: PancakeV3Pool
# # - id: 480 # World // don't have a hypersync instance for world chain
# #   start_block: 0
# #   contracts:
# #   - name: PancakeV3Factory
# #     address: 0x7a5028bda40e7b173c278c5342087826455ea25a
# #   - name: PancakeV3Pool
# - id: 130 # Uni
#   start_block: 0
#   contracts:
#   - name: PancakeV3Factory
#     address: 0x1f98400000000000000000000000000000000003
#   - name: PancakeV3Pool
